=== wiremind/kubernetes-json-schema/master-local/jsonschemaprops.json
{
  "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).",
  "properties": {
    "$ref": {
      "type": [
        "string",
        "null"
      ]
    },
    "$schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "additionalItems": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    },
    "additionalProperties": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    },
    "allOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "anyOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "default": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    },
    "definitions": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      },
      "type": "object"
    },
    "dependencies": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrStringArray"
      },
      "type": "object"
    },
    "description": {
      "type": [
        "string",
        "null"
      ]
    },
    "enum": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "example": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    },
    "exclusiveMaximum": {
      "type": "boolean"
    },
    "exclusiveMinimum": {
      "type": "boolean"
    },
    "externalDocs": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.ExternalDocumentation"
    },
    "format": {
      "type": [
        "string",
        "null"
      ]
    },
    "id": {
      "type": [
        "string",
        "null"
      ]
    },
    "items": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray"
    },
    "maxItems": {
      "format": "int64",
      "type": "integer"
    },
    "maxLength": {
      "format": "int64",
      "type": "integer"
    },
    "maxProperties": {
      "format": "int64",
      "type": "integer"
    },
    "maximum": {
      "format": "double",
      "type": "number"
    },
    "minItems": {
      "format": "int64",
      "type": "integer"
    },
    "minLength": {
      "format": "int64",
      "type": "integer"
    },
    "minProperties": {
      "format": "int64",
      "type": "integer"
    },
    "minimum": {
      "format": "double",
      "type": "number"
    },
    "multipleOf": {
      "format": "double",
      "type": "number"
    },
    "not": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
    },
    "nullable": {
      "type": "boolean"
    },
    "oneOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "pattern": {
      "type": [
        "string",
        "null"
      ]
    },
    "patternProperties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      },
      "type": "object"
    },
    "properties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      },
      "type": "object"
    },
    "required": {
      "items": {
        "type": "string"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "title": {
      "type": [
        "string",
        "null"
      ]
    },
    "type": {
      "type": [
        "string",
        "null"
      ]
    },
    "uniqueItems": {
      "type": "boolean"
    }
  },
  "type": "object",
  "$schema": "http://json-schema.org/schema#"
}

=== wiremind/kubernetes-json-schema/master-standalone-strict/daemonsetstatus.json
{
  "description": "DaemonSetStatus represents the current status of a daemon set.",
  "properties": {
    "collisionCount": {
      "description": "Count of hash collisions for the DaemonSet. The DaemonSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.",
      "format": "int32",
      "type": "integer"
    },
    "conditions": {
      "description": "Represents the latest available observations of a DaemonSet's current state.",
      "items": {
        "description": "DaemonSetCondition describes the state of a DaemonSet at a certain point.",
        "properties": {
          "lastTransitionTime": {
            "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
            "format": "date-time",
            "type": [
              "string",
              "null"
            ]
          },
          "message": {
            "description": "A human readable message indicating details about the transition.",
            "type": [
              "string",
              "null"
            ]
          },
          "reason": {
            "description": "The reason for the condition's last transition.",
            "type": [
              "string",
              "null"
            ]
          },
          "status": {
            "description": "Status of the condition, one of True, False, Unknown.",
            "type": "string"
          },
          "type": {
            "description": "Type of DaemonSet condition.",
            "type": "string"
          }
        },
        "required": [
          "type",
          "status"
        ],
        "type": "object",
        "additionalProperties": false
      },
      "type": [
        "array",
        "null"
      ],
      "x-kubernetes-patch-merge-key": "type",
      "x-kubernetes-patch-strategy": "merge"
    },
    "currentNumberScheduled": {
      "description": "The number of nodes that are running at least 1 daemon pod and are supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/",
      "format": "int32",
      "type": "integer"
    },
    "desiredNumberScheduled": {
      "description": "The total number of nodes that should be running the daemon pod (including nodes correctly running the daemon pod). More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/",
      "format": "int32",
      "type": "integer"
    },
    "numberAvailable": {
      "description": "The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds)",
      "format": "int32",
      "type": "integer"
    },
    "numberMisscheduled": {
      "description": "The number of nodes that are running the daemon pod, but are not supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/",
      "format": "int32",
      "type": "integer"
    },
    "numberReady": {
      "description": "The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and ready.",
      "format": "int32",
      "type": "integer"
    },
    "numberUnavailable": {
      "description": "The number of nodes that should be running the daemon pod and have none of the daemon pod running and available (ready for at least spec.minReadySeconds)",
      "format": "int32",
      "type": "integer"
    },
    "observedGeneration": {
      "description": "The most recent generation observed by the daemon set controller.",
      "format": "int64",
      "type": "integer"
    },
    "updatedNumberScheduled": {
      "description": "The total number of nodes that are running updated daemon pod",
      "format": "int32",
      "type": "integer"
    }
  },
  "required": [
    "currentNumberScheduled",
    "numberMisscheduled",
    "desiredNumberScheduled",
    "numberReady"
  ],
  "type": "object",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}
